### PR TITLE
repair vad.rs

### PR DESCRIPTION
**Pull request by oligamiq**
I get error:
index out of bounds: the len is 0 but the index is 0

Panic is very surprising!

I think that this is reverse.

### CODE REVIEW

**Review by jbrough — APPROVED** [review]

**Comment by jbrough** [comment]
thank you for this - that was a pretty silly mistake on my part.

but yep you'd expect the compiler to pick up on that sort of error, out of bounds errors will panic with rust and you can't lean on the compiler so much to guard against them.

**Comment by jkawamoto** [comment]
Could you please publish v0.2.4?

**Comment by jbrough** [comment]
apologies - done!

**Comment by jkawamoto** [comment]
Thank you!

**Pull request merged**
